# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Make project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: bash ./build.sh

    - name: Pack
      run: tar -cf UDISK.tar UDISK
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: UDISK.tar
        path: UDISK.tar
